apiVersion: v1
kind: Pod 
metadata:
  name: pod-teste-docker-kubernetes
  labels:
    app: teste2
spec: 
  containers:
    - name: web
      image: vitorcostasilva/teste_docker_kubernetes:v1
      ports:
        - containerPort: 55002
