apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-teste-docker-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teste2
    template: 
      metadata:
        app: teste2
      spec: 
        containers:
          - name: web
            image: vitorcostasilva/teste_docker_kubernetes:v1
            ports:
              - containerPort: 55002